name = "Spoken Python"
path_suffixes = ["spk"]
line_comments = ["comment ", "aside "]
block_comment = ["as an aside ", ""]
brackets = [
  { start = "open ", end = "close ", close = true, newline = true },
]
word_characters = ["_"]
