[package]
name = "spoken-python"
version = "0.1.0"
description = "Spoken Python language support for Zed"
authors = ["Rowan Callahan"]
repository = "https://github.com/rowancallahan/speaky"
schema_version = 1

[grammars.spoken_python]
repository = "https://github.com/rowancallahan/speaky"
rev = "15b1c779fefe907198b49a7ad5d60aba1c74c289"
path = "tree-sitter-spoken-python"
