[package]
name = "spoken-python"
version = "0.1.0"
description = "Spoken Python language support for Zed"
authors = ["Rowan Callahan"]
repository = "https://github.com/rowancallahan/speaky"
schema_version = 1

[grammars.spoken_python]
repository = "https://github.com/rowancallahan/speaky"
rev = "cbd9466afbfa538fd8f98cf74db3ae245708e45f"
path = "tree-sitter-spoken-python"
